apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: todo-app
  name: {{ .Values.todoApp.service.name }}
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: todo-app
  type: {{ .Values.todoApp.service.type }}
status:
  loadBalancer: {}
