apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    component: main
  name: sentence
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      {{ if and (eq .Values.sentences.service.type "NodePort") .Values.sentences.service.nodePort -}}
      nodePort: {{ .Values.sentences.service.nodePort }}
      {{- end }}
  selector:
    app: sentences
    component: main
  type: {{ .Values.sentences.service.type }}
