apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    component: age
  name: sentence-age
spec:
  selector:
    matchLabels:
      app: sentences
      component: age
  template:
    metadata:
      labels:
        app: sentences
        component: age
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
    spec:
      #priorityClassName: medium-priority
      containers:
      - image: releasepraqma/age:latest
        imagePullPolicy: Always
        name: sentences
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 0.25
