apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.mysql.service.name }}
  name: {{ .Values.mysql.service.name }}
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysql
  type: {{ .Values.mysql.service.type }}
status:
  loadBalancer: {}
