apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    component: main
  name: sentence
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sentences
    component: main
  type: NodePort
